description: User application settings
type: object
properties:
  language:
    type: string
    description: The language the user has selected
    enum: [en, af, de, fr, nl, xh, zu]
required:
  - language
